groups:
- name: main
  jobs:
  - unit-tests
  - deploy-app
  - load-tests
  - promote-new-version

resources:
- name: application
  type: git
  source:
    branch: master
    uri: https://github.com/warroyo/ops-workshop.git
- name: PWS
  type: cf
  source:
    api: ((pws-api))
    organization: ((pws-organization))
    username: ((deploy-username))
    password: ((deploy-password))
    skip_cert_check: true
    space: ((pws-space))

jobs:
- name: unit-tests
  serial: true
  public: true
  plan:
  - get: application
    trigger: true
  - task: run-unit-tests
    file: application/demos/cicd/bg-app-deploy/ci/tasks/unit-tests.yml

- name: deploy-app
  serial: true
  public: true
  plan:
  - get: application
    trigger: true
    passed:
      - unit-tests
  - task: get-current-app-color
    file: application/demos/cicd/bg-app-deploy/ci/tasks/current-app-get-info.yml
    params:
      PWS_APP_SUFFIX: ((pws-app-suffix))
      PWS_API: ((pws-api))
      PWS_ORG: ((pws-organization))
      PWS_USER: ((deploy-username))
      PWS_PWD: ((deploy-password))
      PWS_SPACE: ((pws-space))
  - task: prepare-app-manifest
    file: application/demos/cicd/bg-app-deploy/ci/tasks/app-manifest-prep.yml
    params:
      PWS_APP_SUFFIX: ((pws-app-suffix))
  - put: PWS
    params:
      manifest: app-manifest-output/manifest.yml
      path: application/demos/cicd/bg-app-deploy/bgd-app

- name: load-tests
  serial: true
  public: true
  plan:
  - get: application
    trigger: true
    passed:
      - deploy-app
  - task: get-current-app-color
    file: application/demos/cicd/bg-app-deploy/ci/tasks/current-app-get-info.yml
    params:
      PWS_APP_SUFFIX: ((pws-app-suffix))
      PWS_API: ((pws-api))
      PWS_ORG: ((pws-organization))
      PWS_USER: ((deploy-username))
      PWS_PWD: ((deploy-password))
      PWS_SPACE: ((pws-space))
  - task: run-load-tests
    file: application/demos/cicd/bg-app-deploy/ci/tasks/load-tests.yml
    params:
      PWS_APP_SUFFIX: ((pws-app-suffix))
      PWS_APP_DOMAIN: ((pws-app-domain))

- name: promote-new-version
  serial: true
  public: true
  plan:
  - get: application
    trigger: true
    passed:
      - load-tests
  - task: get-current-app-color
    file: application/demos/cicd/bg-app-deploy/ci/tasks/current-app-get-info.yml
    params:
      PWS_APP_SUFFIX: ((pws-app-suffix))
      PWS_API: ((pws-api))
      PWS_ORG: ((pws-organization))
      PWS_USER: ((deploy-username))
      PWS_PWD: ((deploy-password))
      PWS_SPACE: ((pws-space))
  - task: switch-app-routes
    file: application/demos/cicd/bg-app-deploy/ci/tasks/update-routes.yml
    params:
      PWS_APP_SUFFIX: ((pws-app-suffix))
      PWS_APP_DOMAIN: ((pws-app-domain))
      PWS_API: ((pws-api))
      PWS_ORG: ((pws-organization))
      PWS_USER: ((deploy-username))
      PWS_PWD: ((deploy-password))
      PWS_SPACE: ((pws-space))
