#!/bin/bash

set -e

export NEXT_APP_COLOR=$(cat ./current-app-info/next-app.txt)
export NEXT_APP_URL=http://$NEXT_APP_COLOR-$PWS_APP_SUFFIX.$PWS_APP_DOMAIN/

echo "Running artillery load tests..."

artillery quick --duration 10 --rate 10 $NEXT_APP_URL
