// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using account_api;

namespace account_api.Migrations
{
    [DbContext(typeof(AccountDb))]
    partial class AccountDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("account_api.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("First")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Last")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "bob.smith@gmail.com",
                            First = "bob",
                            Last = "smith"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jim.roberts@gmail.com",
                            First = "jim",
                            Last = "roberts"
                        },
                        new
                        {
                            Id = 3,
                            Email = "alison.jacobs@aol.com",
                            First = "alison",
                            Last = "jacobs"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
